"""Deterministic, rebuildable Markdown indexes."""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Any

from research_os.domain.models import ResearchObject
from research_os.domain.policies import is_iso_date
from research_os.repositories.transaction import FileTransaction

INDEX_PATHS = {
    "source": Path("08_Indexes/Source_Index.md"),
    "event": Path("08_Indexes/Event_Index.md"),
    "thesis": Path("08_Indexes/Thesis_Index.md"),
    "company": Path("08_Indexes/Company_Index.md"),
    "impact_assertion": Path("08_Indexes/Impact_Index.md"),
}


def display(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, list):
        return ", ".join(str(item) for item in value)
    if isinstance(value, float):
        return f"{value:.2f}"
    return str(value)


def index_date(objects: list[ResearchObject]) -> str:
    values = [
        str(obj.metadata.get("updated_at"))
        for obj in objects
        if obj.object_type != "job"
        if is_iso_date(obj.metadata.get("updated_at"))
    ]
    return max(values, default=date.today().isoformat())


def index_header(title: str, objects: list[ResearchObject]) -> list[str]:
    return [
        f"# {title}",
        "",
        "<!-- Generated by 09_Automation/research_os.py index. -->",
        "",
        f"更新时间：{index_date(objects)}",
        "",
    ]


def render_source_index(objects: list[ResearchObject]) -> str:
    rows = sorted(
        (obj for obj in objects if obj.object_type == "source"),
        key=lambda obj: obj.object_id,
    )
    lines = index_header("Source Index", rows)
    lines += [
        "| Source ID | 标题 | 类型 | 发布者 | 等级 | 归档状态 | 审核状态 |",
        "|---|---|---|---|---|---|---|",
    ]
    for obj in rows:
        meta = obj.metadata
        lines.append(
            "| "
            + " | ".join(
                (
                    obj.object_id,
                    display(meta.get("title")),
                    display(meta.get("source_type")),
                    display(meta.get("publisher")),
                    display(meta.get("source_grade")),
                    display(meta.get("processing_status")),
                    display(meta.get("review_status")),
                )
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def render_event_index(objects: list[ResearchObject]) -> str:
    rows = sorted(
        (obj for obj in objects if obj.object_type == "event"),
        key=lambda obj: obj.object_id,
    )
    lines = index_header("Event Index", rows)
    lines += [
        "| Event ID | 日期 | 标题 | Thesis | 置信度 | 审核状态 |",
        "|---|---|---|---|---:|---|",
    ]
    for obj in rows:
        meta = obj.metadata
        lines.append(
            "| "
            + " | ".join(
                (
                    obj.object_id,
                    display(meta.get("event_date")),
                    display(meta.get("title")),
                    display(meta.get("thesis_links")),
                    display(meta.get("confidence")),
                    display(meta.get("review_status")),
                )
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def render_impact_assertion_index(objects: list[ResearchObject]) -> str:
    rows = sorted(
        (obj for obj in objects if obj.object_type == "impact_assertion"),
        key=lambda obj: obj.object_id,
    )
    lines = index_header("Impact Assertion Index", rows)
    lines += [
        "| Impact ID | 触发 Event | Target | 类型 | 方向 | Horizon | 置信度 | 状态 |",
        "|---|---|---|---|---|---|---:|---|",
    ]
    for obj in rows:
        meta = obj.metadata
        lines.append(
            "| "
            + " | ".join(
                (
                    obj.object_id,
                    display(meta.get("subject_id")),
                    display(meta.get("target_id")),
                    display(meta.get("impact_type")),
                    display(meta.get("direction")),
                    display(meta.get("horizon")),
                    display(meta.get("confidence")),
                    display(meta.get("review_status")),
                )
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def render_thesis_index(objects: list[ResearchObject]) -> str:
    rows = sorted(
        (obj for obj in objects if obj.object_type == "thesis"),
        key=lambda obj: obj.object_id,
    )
    lines = index_header("Thesis Index", rows)
    lines += [
        "| Thesis ID | 判断 | 置信度 | 支持 | 反面 | Thesis 状态 | 审核状态 |",
        "|---|---|---:|---:|---:|---|---|",
    ]
    for obj in rows:
        meta = obj.metadata
        supporting = meta.get("supporting_evidence", [])
        contradicting = meta.get("contradicting_evidence", [])
        lines.append(
            "| "
            + " | ".join(
                (
                    obj.object_id,
                    display(meta.get("title")),
                    display(meta.get("confidence")),
                    str(len(supporting) if isinstance(supporting, list) else 0),
                    str(len(contradicting) if isinstance(contradicting, list) else 0),
                    display(meta.get("thesis_status")),
                    display(meta.get("review_status")),
                )
            )
            + " |"
        )
    lines += [
        "",
        "说明：支持和反面数量来自 Thesis front matter；contextual Event 不计入。",
    ]
    return "\n".join(lines) + "\n"


def render_company_index(objects: list[ResearchObject]) -> str:
    rows = sorted(
        (obj for obj in objects if obj.object_type == "company"),
        key=lambda obj: obj.object_id,
    )
    lines = index_header("Company Index", rows)
    lines += [
        "| Company ID | 公司 | Evidence 数量 | Related entities | 审核状态 |",
        "|---|---|---:|---|---|",
    ]
    for obj in rows:
        meta = obj.metadata
        evidence = meta.get("evidence_ids", [])
        lines.append(
            "| "
            + " | ".join(
                (
                    obj.object_id,
                    display(meta.get("title")),
                    str(len(evidence) if isinstance(evidence, list) else 0),
                    display(meta.get("related_entities")),
                    display(meta.get("review_status")),
                )
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def render_project_registry(objects: list[ResearchObject]) -> str:
    rows = sorted(
        (obj for obj in objects if obj.object_type == "project"),
        key=lambda obj: obj.object_id,
    )
    lines = [
        "# Research Project Registry",
        "",
        "<!-- Generated from structured Project objects. -->",
        "",
        f"更新时间：{index_date(objects)}",
        "",
        "| Project ID | Research question | Owner | Charter | Queue | "
        "Current Report | Review cadence | Next review | Status |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for obj in rows:
        meta = obj.metadata
        lines.append(
            f"| {obj.object_id} | {display(meta.get('research_question'))} | "
            f"{display(meta.get('owner'))} | "
            f"`{display(meta.get('charter_path'))}` | "
            f"`{display(meta.get('queue_path'))}` | "
            f"{display(meta.get('current_report_id'))} | "
            f"{display(meta.get('review_cadence'))} | "
            f"{display(meta.get('next_review_date'))} | "
            f"{display(meta.get('status'))} |"
        )
    lines += [
        "",
        "## Registration rules",
        "",
        "- 新主题先建立 Charter、边界和成功标准，再标记为 active。",
        "- 同一时间最多保持三个 active 主题，超过时必须说明研究资源分配。",
        "- 每个 active 项目必须有 Owner、Queue、复盘周期和下一次复盘日期。",
        "- final Report 必须对应已注册项目。",
        "- 项目归档时保留永久 ID、报告、指标快照和复盘记录。",
    ]
    return "\n".join(lines) + "\n"


def render_action_register(objects: list[ResearchObject]) -> str:
    rows = sorted(
        (obj for obj in objects if obj.object_type == "action"),
        key=lambda obj: (str(obj.metadata.get("due_date")), obj.object_id),
    )
    lines = [
        "# Research Action Register",
        "",
        "<!-- Generated from structured Action objects. -->",
        "",
        f"更新时间：{index_date(objects)}",
        "",
        "状态只使用：`open`、`in_progress`、`done`、`cancelled`。",
        "",
        "| Action ID | Projects | Action | Owner | Due date | "
        "Success evidence | Status |",
        "|---|---|---|---|---|---|---|",
    ]
    for obj in rows:
        meta = obj.metadata
        lines.append(
            f"| {obj.object_id} | "
            f"{', '.join(meta.get('project_ids', []))} | "
            f"{display(meta.get('title'))} | {display(meta.get('owner'))} | "
            f"{display(meta.get('due_date'))} | "
            f"{display(meta.get('success_evidence'))} | "
            f"{display(meta.get('status'))} |"
        )
    return "\n".join(lines) + "\n"


def render_review_index(objects: list[ResearchObject]) -> str:
    rows = sorted(
        (obj for obj in objects if obj.object_type == "review"),
        key=lambda obj: obj.object_id,
    )
    lines = [
        "# Review Decision Index",
        "",
        "<!-- Generated from immutable Review Decision objects. -->",
        "",
        f"更新时间：{index_date(objects)}",
        "",
        "| Review ID | Date | Decision | Targets | Reviewer | Projects |",
        "|---|---|---|---|---|---|",
    ]
    for obj in rows:
        meta = obj.metadata
        lines.append(
            f"| {obj.object_id} | {display(meta.get('reviewed_at'))} | "
            f"{display(meta.get('decision'))} | "
            f"{', '.join(meta.get('target_ids', []))} | "
            f"{display(meta.get('reviewer'))} | "
            f"{', '.join(meta.get('project_ids', []))} |"
        )
    return "\n".join(lines) + "\n"


def render_home_dashboard(objects: list[ResearchObject]) -> str:
    projects = sorted(
        (obj for obj in objects if obj.object_type == "project"),
        key=lambda obj: obj.object_id,
    )
    pending = sorted(
        (obj for obj in objects if obj.metadata.get("review_status") == "pending"),
        key=lambda obj: (obj.object_type, obj.object_id),
    )
    actions = sorted(
        (
            obj
            for obj in objects
            if obj.object_type == "action"
            and obj.metadata.get("status") in {"open", "in_progress"}
        ),
        key=lambda obj: (str(obj.metadata.get("due_date")), obj.object_id),
    )
    theses = sorted(
        (obj for obj in objects if obj.object_type == "thesis"),
        key=lambda obj: obj.object_id,
    )
    reports = sorted(
        (obj for obj in objects if obj.object_type == "report"),
        key=lambda obj: str(obj.metadata.get("updated_at", "")),
        reverse=True,
    )
    failed_jobs = sorted(
        (
            obj
            for obj in objects
            if obj.object_type == "job" and obj.metadata.get("status") == "failed"
        ),
        key=lambda obj: str(obj.metadata.get("started_at", "")),
        reverse=True,
    )
    lines = index_header("AI Research OS Home", objects)
    lines += [
        "> Obsidian fallback dashboard. Rebuilt from canonical Markdown objects.",
        "",
        "## Projects",
        "",
    ]
    lines.extend(
        f"- [[{obj.object_id}]] — {display(obj.metadata.get('title'))} · "
        f"{display(obj.metadata.get('status'))} · next review "
        f"{display(obj.metadata.get('next_review_date'))}"
        for obj in projects
    )
    if not projects:
        lines.append("- None")
    lines += [
        "",
        "## Review queue",
        "",
        "| Object | Type | Updated |",
        "|---|---|---|",
    ]
    lines.extend(
        f"| [[{obj.object_id}]] | {obj.object_type} | "
        f"{display(obj.metadata.get('updated_at'))} |"
        for obj in pending
    )
    if not pending:
        lines.append("| — | No pending objects | — |")
    lines += [
        "",
        "## Thesis health",
        "",
        "| Thesis | Confidence | Supporting | Contradicting |",
        "|---|---:|---:|---:|",
    ]
    lines.extend(
        f"| [[{obj.object_id}]] | {display(obj.metadata.get('confidence'))} | "
        f"{len(obj.metadata.get('supporting_evidence', []))} | "
        f"{len(obj.metadata.get('contradicting_evidence', []))} |"
        for obj in theses
    )
    if not theses:
        lines.append("| — | — | — | — |")
    lines += [
        "",
        "## Open actions",
        "",
        "| Action | Owner | Due | Status |",
        "|---|---|---|---|",
    ]
    lines.extend(
        f"| [[{obj.object_id}]] | {display(obj.metadata.get('owner'))} | "
        f"{display(obj.metadata.get('due_date'))} | "
        f"{display(obj.metadata.get('status'))} |"
        for obj in actions
    )
    if not actions:
        lines.append("| — | — | — | No open actions |")
    lines += [
        "",
        "## Recent reports",
        "",
    ]
    lines.extend(
        f"- [[{obj.object_id}]] — {display(obj.metadata.get('title'))} · "
        f"{display(obj.metadata.get('status'))}"
        for obj in reports[:10]
    )
    if not reports:
        lines.append("- None")
    lines += [
        "",
        "## Failed jobs",
        "",
    ]
    lines.extend(
        f"- [[{obj.object_id}]] — {display(obj.metadata.get('job_name'))}: "
        f"{display(obj.metadata.get('message'))}"
        for obj in failed_jobs[:10]
    )
    if not failed_jobs:
        lines.append("- None")
    return "\n".join(lines) + "\n"


def render_indexes(objects: list[ResearchObject]) -> dict[Path, str]:
    return {
        INDEX_PATHS["source"]: render_source_index(objects),
        INDEX_PATHS["event"]: render_event_index(objects),
        INDEX_PATHS["thesis"]: render_thesis_index(objects),
        INDEX_PATHS["company"]: render_company_index(objects),
        INDEX_PATHS["impact_assertion"]: render_impact_assertion_index(objects),
        Path("05_Research/Project_Registry.md"): render_project_registry(objects),
        Path("05_Research/Reviews/Action_Register.md"): render_action_register(objects),
        Path("08_Indexes/Review_Index.md"): render_review_index(objects),
        Path("08_Indexes/Home_Dashboard.md"): render_home_dashboard(objects),
    }


def render_project_indexes(
    objects: list[ResearchObject],
    project_id: str,
) -> dict[Path, str]:
    if not any(
        obj.object_type == "project" and obj.object_id == project_id for obj in objects
    ):
        raise ValueError(f"unknown project id {project_id}")
    scoped = [
        obj
        for obj in objects
        if obj.object_id == project_id
        or project_id in obj.metadata.get("project_ids", [])
    ]
    prefix = Path("08_Indexes/Projects") / project_id
    return {
        prefix / path.name: content for path, content in render_indexes(scoped).items()
    }


def index_drift(root: Path, rendered: dict[Path, str]) -> list[Path]:
    drift: list[Path] = []
    for relative, expected in rendered.items():
        path = root / relative
        try:
            actual = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            actual = ""
        if actual != expected:
            drift.append(relative)
    return drift


def apply_indexes(root: Path, rendered: dict[Path, str]) -> None:
    transaction = FileTransaction(root)
    for relative, content in rendered.items():
        if (root / relative).exists():
            transaction.stage_replace(relative, content)
        else:
            transaction.stage_create(relative, content)
    transaction.commit()
